name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools==47.3.0 wheel==0.34.2 twine==3.1.1

    - name: Prepare package
      run: |
        curl -Lo thrift.tar.gz https://github.com/apache/thrift/archive/v0.14.1.tar.gz
        sha256sum --check checksums.txt
        tar -x --wildcards --exclude --no-anchored "thrift*/lib/py/" --strip-components=3 -f thrift.tar.gz
        patch < setup_py.patch

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist
        twine upload dist/*

